# Generated by Django 4.1 on 2022-09-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Profile', '0002_mensajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
    ]
