# Generated by Django 4.1 on 2022-09-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_Profile', '0006_mensajes_receiver_mensajes_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='sender',
        ),
    ]
