# Generated by Django 4.1 on 2022-09-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_B_1', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
